name: Continuous Deployment

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Make Build Script Executable
        run: chmod +x build_lambdas.sh

      - name: Build All Lambdas
        run: ./build_lambdas.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init & Apply App
        run: |
          cd app
          terraform init
          terraform apply -auto-approve \
            -var="smtp_username=${{ secrets.SMTP_USERNAME }}" \
            -var="smtp_password=${{ secrets.SMTP_PASSWORD }}" \
            -var="cors_allowed_origins=${{ secrets.CORS_ALLOWED_ORIGINS }}"